import React from 'react';
import { 
  ScanLine, 
  Search, 
  Headset, 
  MessageSquareText, 
  Briefcase, 
  Banknote, 
  ArrowRightLeft, 
  PieChart,
  CreditCard,
  Receipt,
  ArrowDownLeft,
  Building2,
  Flame,
  PiggyBank,
  Crown,
  Ticket,
  TrendingUp,
  MoreHorizontal,
  Home,
  Users,
  Coffee,
  User,
  X,
  Send,
  Globe,
  Clock,
  Shield,
  Zap,
  FileText,
  Bitcoin,
  Newspaper,
  BarChart3,
  ChevronRight,
  Wallet
} from 'lucide-react';

export const Icons = {
  Scan: ScanLine,
  Search: Search,
  Headset: Headset,
  Message: MessageSquareText,
  Savings: Briefcase,
  Borrow: Banknote,
  Transfer: ArrowRightLeft,
  Overview: PieChart,
  CreditCard: CreditCard,
  Receipt: Receipt,
  Deposit: ArrowDownLeft,
  City: Building2,
  Hot: Flame,
  Pension: PiggyBank,
  Member: Crown,
  Ticket: Ticket,
  Wealth: TrendingUp,
  More: MoreHorizontal,
  Home: Home,
  Community: Users,
  Life: Coffee,
  Me: User,
  Close: X,
  Send: Send,
  Lang: Globe,
  Clock: Clock,
  Shield: Shield,
  Zap: Zap,
  File: FileText,
  Bitcoin: Bitcoin,
  News: Newspaper,
  Chart: BarChart3,
  ChevronRight: ChevronRight,
  Wallet: Wallet,
  // Added aliases for direct access by name
  TrendingUp: TrendingUp,
  Crown: Crown,
  MoreHorizontal: MoreHorizontal,
  User: User,
  ArrowRightLeft: ArrowRightLeft,
  PieChart: PieChart,
  Banknote: Banknote,
  FileText: FileText
};